#!/bin/bash
IFACE="$1"
STATE="$2"

CONF="/etc/dhcp/dhcpd.conf"
echo "$(date) Dispatcher called for $IFACE with state $STATE route $IP4_GATEWAY" >> /var/log/nm-dispatcher.log
    case "$STATE" in
        connectivity-change)
	if [ "$CONNECTIVITY_STATE" != "FULL" ]; then
            # Interface is up (cable plugged, carrier present)
            # Ensure subnet block exists
            if ! grep -q "subnet 192.168.3.0" "$CONF"; then
                cat >> "$CONF" <<EOF
subnet 192.168.3.0 netmask 255.255.255.0 {
  range 192.168.3.10 192.168.3.200;
  option routers 192.168.3.1;
  option domain-name-servers 8.8.8.8, 1.1.1.1;
}
EOF
echo "$(date) Dispatcher add subnet $CONNECTIVITY_STATE" >> /var/log/nm-dispatcher.log
            fi
            systemctl restart isc-dhcp-server.service
	fi
            ;;
        dhcp4-change)
            # Interface is down (cable unplugged, carrier lost)
            # Remove subnet block
            sed -i '/subnet 192.168.3.0 netmask/,/}/d' "$CONF"
            systemctl restart isc-dhcp-server.service
echo "$(date) Remove Subnet" >> /var/log/nm-dispatcher.log
            ;;
        *)
            # Ignore other states
            ;;
    esac
